@host=http://localhost:5115
@adminId=778bbbcf-312d-42ca-ade8-566bd9b3ce46

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType":"Free",
    "AdminId": "{{adminId}}"
}


