@host=http://localhost:5115
@adminId=3f2504e0-4f89-11d3-9a0c-0305e82c3301

POST {{host}}/Subscriptions
Content-Type: application/json

{
    "SubscriptionType":"Free",
    "AdminId": "{{adminId}}"
}


